print("Please enter the number of lives: ")
health = int(input())
print("\nPlease enter the energy level: ")
energy = int(input())
print("\nPlease enter the shield level:  ")
shield = int(input())
print("\nHealth has been set")
print("Lives:",  "\u2665"*health)
print("Energy:",  "\u2666"*energy)
print("Shields:",  "\u2666"*shield)